### ISSUE TITLE
settings.json の設定が効かない？

### ISSUE THREAD

**Issue by takasehideki** [h7ga40/azure_iot_hub_peach#2]
まず，`File > Open Workspace...`でGitRepo直下の`azure_iot_hub_peach.code-workspace`を選択してVSCodeを開いています．これは合っているでしょうか？
（`File > Open Folder...`で`app_iothub_client`を開く方法もあると思います．こちらでは少し挙動は変わる気がします）

そして，`asp3_dcre/.vscode/settings.json`の定義，例えば，
```
    "terminal.integrated.env.windows": {
        "PATH": "C:\\Program Files (x86)\\GNU Tools ARM Embedded\\6 2017-q2-update\\bin;C:\\Ruby24-x64\\bin",
~~~
        "TCINSTALL": "/C:/Program Files (x86)/GNU Tools ARM Embedded/6 2017-q2-update/",
```
がビルドには効いていない気がします．
`asp3_dcre/Debug/Makefile`の242行目，
```
MALLOC_LIB = "${TCINSTALL}arm-none-eabi/lib/thumb/v7-ar/fpv3/hard/libc.a"
```
のパスを直書きしないとmakeが通りません．

あとそもそも，makeはmsys64で走るとは思うのですが，本当にそうなのか自信がありません．
元からCmd.exeをLinuxライクにするツールであるGowを導入しているのですが，そのmake.exeとcmdで走っているような気もします．
VSCode画面下側のTERMINALの`Select Defaut Shell`で，`C:\msys64\msys2.exe`を選択できると良いのですけど．

**Comment by takasehideki** [comment]
msys64 上では， `pacman -S make` は導入済みです．使われているかは分からないんですが，，，

**Comment by h7ga40** [comment]
各プロジェクトのsetting.jsonの設定より、*.code-workspaceの設定が優先されるようです。ワークスペースでなく各フォルダを開いたときにsetting.jsonの設定が有効になるようです。
MakefileのMALLOC_LIBのパスについては、*.code-workspaceの設定を変えてもらう必要があります。

**Comment by takasehideki** [comment]
これはまず，どういうポリシーで環境準備してもらうかという問題でもあります．
- arm-none-eabi と Ruby の導入時に環境変数のチェックしてもらう
- arm-none-eabi は必ずデフォルトの "C:\Program Files (x86)"にしてもらう
- GNU MakeなりGowなりもインストールしてもらう

ってして，${TCINSTALL} は直書きにしちゃうのもアリな気がします．

そしてこうすれば，そもそもmsys64が要らなくなりそうです（検証中です

**Comment by h7ga40** [comment]
TCINSTALLはe2studioで設定される環境変数で、VSCodeではそれに合わせているという経緯もあります。今のところは両対応で行きたいと思います。

**Comment by takasehideki** [comment]
あっなるほど，了解です．
ではコチラ側でなんとかなるように，もう少し調べてみます．

**Comment by takasehideki** [comment]
コレも私のミスでしたねスミマセン，，，
備忘録として原因と対策を残してcloseとしておきます

原因：初回のビルド時またはターミナル起動時に下記画面が表示されるが，「許可」を選択しないといけない（許可しないとmsys2との連携ができなくなる）
![vscode_shell](https://user-images.githubusercontent.com/23649012/60151751-ecbda780-9818-11e9-97e7-9a79ba6f27ee.JPG)

対策：
1. ディレクトリの名前またはパスを変える（ユーザ設定の何処かに記録されてしまうみたい）
2. VSCodeを，アンインストール＆ユーザー設定や拡張機能も削除してから，インストールし直す
https://www.atmarkit.co.jp/ait/articles/1810/12/news026.html#settingandext
